\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		r1 d1 a1 g1 a1

		% este es el dia y el lugar...
		d1 a1 g1 a1
		d1 a1 g1 a1
		% este es el dia y el lugar...
		d1 a1 g1 a1
		d1 a1 g1 a1 a1

		% alabanzas al sennor...
		d1 b1:m g1 a1
		d1 b1:m g1 a2

		% y dar gracias al sennor...
		\set chordChanges = ##f
		a4 g4
		\set chordChanges = ##t
		fis1:m b1:m g1
		\set chordChanges = ##f
		a4 a4
		\set chordChanges = ##t
		a2
		d1 a1

		% alabanzas al sennor...
		d1 b1:m g1 a1
		d1 b1:m g1 a2

		% y dar gracias al sennor...
		\set chordChanges = ##f
		a4 g4
		\set chordChanges = ##t
		fis1:m b1:m g1
		\set chordChanges = ##f
		a4 a4
		\set chordChanges = ##t
		a2
		d1 d1
	}
